---
tap_install:
  values: 
        shared:
          ingress_domain: "akslab.tap.fynesy.com"
          ingress_issuer: "letsencrypt-production"


        ceip_policy_disclosed: true

        profile: full 
        supply_chain: basic 

        ootb_supply_chain_basic: 
          registry:
            server: "index.docker.io"
            repository: "fynesy"
          gitops:
            ssh_secret: ""

        ootb_supply_chain_testing_scanning:
          registry:
            server: "index.docker.io"
            repository: "fynesy"
          gitops:
            ssh_secret: ""

        contour:
          envoy:
            service:
              type: LoadBalancer 

        buildservice:
          kp_default_repository: "fynesy/buildservice"

        tap_gui:
          service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
          metadataStoreAutoconfiguration: true 
          app_config:
            auth:
              allowGuestAccess: true
            catalog:
              locations:
                - type: url
                  target: http://github.com/tfynes-pivotal/tapblankcatalog/blob/main/catalog-info.yaml

        metadata_store:
          ns_for_export_app_cert: "*"
          app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

        scanning:
          metadataStore:
            url: "" 

        grype:
          namespace: "default"
          targetImagePullSecret: "tap-registry"
          # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

        policy:
          tuf_enabled: false 

        cnrs:
          domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'

        api_portal:
          apiPortalServer:
            #!sourceUrls: https://petstore.swagger.io/v2/swagger.json,http://10.0.166.161/openapi
            sourceUrls: https://petstore.swagger.io/v2/swagger.json,http://scg-operator.tap-install.svc.cluster.local/openapi
            trustInsecureSourceUrls: true
          sso:
            enabled: true
            secretName: okta-sso  
          # apiKey:
          #   enabled: true
          #   vault:
          #     url: http://10.0.57.66:8200
          #     role: api-portal-role
          #     path: api-portal-for-vmware-tanzu
          #   serviceAccount:
          #     create: true
          #     name: api-portal-service-account
          # sso:
          #   enabled: true

        namespace_provisioner:
          controller: false
          gitops_install:
            ref: origin/main
            subPath: clusters/akslab2/cluster-config/namespaces
            url: https://github.com/tfynes-pivotal/tap-gitops-sc
          additional_sources:
          - git:
              ref: origin/main
              subPath: clusters/akslab2/cluster-config/namespaces/namespace-resources
              url: https://github.com/tfynes-pivotal/tap-gitops-sc
            path: _ytt_lib/namespace-resources
        #!  import_data_values_secrets:
        #!   - name: my-dockerhub-credentials
        #!     namespace: tap-install
        #!     create_export: true
        package_overlays:
        - name: api-portal
          secrets:
          - name: api-portal-cm-tls-overlay-secret