apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: tdemo-gateway
  namespace: default
spec:
  count: 1
  host: tdemo.akslab1a.tap.fynesy.com
  api:
    serverUrl: tdemo.akslab1a.tap.fynesy.com
    title: Tanzu Demo APIs
    description: Sample basic SCG + TAP Demos
    version: 0.0.1
    groupID: "tanzu-demo"
    cors:
      allowedOrigins:
      - "https://api-portal.akslab1a.tap.fynesy.com"
      allowedMethods:
      - "GET"
      allowedHeaders:
      - '*'

  serviceAccount:
    name: tdemo-gateway-svc-acc

  extensions:
    secretsProviders:
      - name: vault-api-keys
        vault:
          roleName: api-portal-role
          path: api-portal-for-vmware-tanzu
    filters:
      apiKey:
        enabled: true
        secretsProviderName: vault-api-keys